### ISSUE TITLE
specify version control view directory on command line

### ISSUE THREAD

**Issue by amcpherson** [yousseb/meld#10]
Using the homebrew meld, from a subdirectory of a git repo i can type:

    meld ./

and meld will load automatically with version control view for that directory.  The same for this fork would be great.

**Comment by yousseb** [comment]
I'm trying to figure out a way to remove the wrapper shell script for Meld. Until now, I can't find a way to make the binary find the shared libs without the wrapper..

Meanwhile, you can check this post:
http://www.alexkras.com/how-to-run-meld-on-mac-os-x-yosemite-without-homebrew-macports-or-think/

Which describes how you can have yet another wrapper that allows you to do precisely what you're looking for.

**Comment by CarloQ** [comment]
put this script to /usr/local/bin/meld ~

```
#!/bin/sh

for arg in $@; do
	if [ -e $arg ]; then
		arg="$(cd "$(dirname "${arg}")" && pwd)/$(basename "${arg}")"
	fi
	new_args="$new_args$arg "
done

open -n /Applications/Meld.app --args $new_args

```

**Comment by yousseb** [comment]
osx-7 build should fix this issue. Please give it a shot. No need for extra wrappers..

**Comment by yousseb** [comment]
Try osx-8 instead.
