### ISSUE TITLE
Meld crashes when switching keyboard layouts

### ISSUE THREAD

**Issue by decden** [yousseb/meld#101]
Hello!

I am having the following issue with Meld: whenever I change keyboard layout in Windows, Meld will crash. This can be reproduced 100% of the times on my machine.

### My environment:

 - Meld 3.20.0 (Binary distribution)
 - Windows 10 (1809)
 - US + German + Japanese Keyboard layouts

**Comment by yousseb** [comment]
@kaiw Windows port - not sure who would be the owner.

**Comment by kaiw** [comment]
This has already been reported at https://gitlab.gnome.org/GNOME/meld/issues/424. It's a GTK issue, and is fixed by our current build anyway, so this should definitely be closed.

**Comment by yousseb** [comment]
@kaiw 
Thank you. Closing..
