### ISSUE TITLE
Fix .gitconfig for git difftool --dir to work

### ISSUE THREAD

**Issue by nickie** [yousseb/meld#11]
At least in my case, for `git difftool --dir` to work properly, I had to change the `cmd` in `.gitconfig` as follows (that is, I had to remove `$PWD/` before `$REMOTE`):

```
[difftool "meld"]
  trustExitCode = true
  cmd = open -W -a Meld --args \"$LOCAL\" \"$REMOTE\"
```

Then, it is possible to do `git difftool --dir master`.  **Unfortunately**, this breaks the case where `--dir` is not used, i.e., with this change, `git difftool master -- README.md` will not work anymore.

A fix (or at least a warning in the documentation that you have in your excellent web site) would be very welcome.  Possibly with a wrapper script, if it can't be done otherwise.

**Comment by alaska** [comment]
Yeah, this is a real killer.  Luckily, Meld is git-aware, so you can make an alias to
`open -W -a Meld --args $PWD` that will work in the meantime.

**Comment by nickie** [comment]
You mean, not use `git difftool` but use `Meld` directly instead...  Yes, that's an option, but writing a wrapper script to make `git difftool` work should not be hard.

**Comment by yousseb** [comment]
guys - thanks for the report. 
I've done some work on the wrapper script in osx-7. I doubt that it would fix this issue, though. Can you give me some hint on what/how I can reproduce or what to write in the docs? Check the tip in the docs on the website: https://yousseb.github.io/meld/ - what am I missing?

The killer part, in my opinion, is that until this moment I can't ditch the wrapper script. It's ugly, but basically, the dynamic loader for OSX needs to find GTK using a specific environment variable that cannot be set after the app is started... All the other vars were removed from the script. 

If you know anyway to get around this:
https://github.com/yousseb/meld/blob/master/osx/Meld#L33

Please help/let me know how...

**Comment by yousseb** [comment]
Oh, and please forgive the horrible style in the wrapper script. I only had five minutes to switch from bash to python. Will clean it up on next release..

**Comment by yousseb** [comment]
Use osx-8 instead of osx-7 for testing.

**Comment by nickie** [comment]
I'm submitting a pull request:  yousseb/meld#16.  This should fix this issue.

Then, the documentation tip on your web site should change to:

    [difftool "meld"]
      trustExitCode = true
      cmd = open -W -a Meld --args \"$LOCAL\" \"$REMOTE\"

I suppose this will work similarly for merging, but I haven't tested it:

    [mergetool "meld"]
      trustExitCode = true
      cmd = open -W -a Meld --args --auto-merge \"$LOCAL\" \"$BASE\" \"$REMOTE\" --output=\"$MERGED\"

Notice the `=` in `--output=` there, missing from your current documentation!

**Comment by yousseb** [comment]
Thanks.. Merged the pull request. 

I will test and upload a new build / update docs soon.

**Comment by nickie** [comment]
Splendid.  Just make sure to fix the documentation on https://yousseb.github.io/meld/ (see my previous comment).  I'm closing this issue.
