### ISSUE TITLE
clearlooks has a hardcoded path

### ISSUE THREAD

**Issue by aflat** [yousseb/meld#12]
Version osx-6
When I start it from the command line I get

/Applications/Meld.app/Contents/Resources/meld:180: GtkWarning: dlopen(/Applications/Meld.app/Contents/Resources/lib/gtk-2.0/2.10.0/engines/libclearlooks.so, 1): Library not loaded: /Users/yousseb/gtk/inst/lib/libgtk-quartz-2.0.0.dylib

I have that library installed, just not on that path of course.

**Comment by yousseb** [comment]
You sure this is the osx-6 version? We're on gtk3 for that version..

**Comment by aflat** [comment]
Your right, must have been using an older one.
