### ISSUE TITLE
Warnings thrown when starting from command line

### ISSUE THREAD

**Issue by aflat** [yousseb/meld#13]
Just running from the command line throws a bunch of warnings.

aflat$ /Applications/Meld.app/Contents/MacOS/Meld

/Applications/Meld.app/Contents/Resources/lib:/Applications/Meld.app/Contents/Frameworks
Couldn't bind the translation domain. Some translations won't work.
'module' object has no attribute 'bind_textdomain_codeset'
/Applications/Meld.app/Contents/Resources/lib/python2.7/site-packages.zip/meld/meldwindow.py:193: Warning: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
/Applications/Meld.app/Contents/Resources/lib/python2.7/site-packages.zip/meld/ui/gnomeglade.py:45: Warning: The property GtkAlignment:yalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
/Applications/Meld.app/Contents/Resources/lib/python2.7/site-packages.zip/meld/ui/gnomeglade.py:45: Warning: The property GtkAlignment:xscale is deprecated and shouldn't be used anymore. It will be removed in a future version.
/Applications/Meld.app/Contents/Resources/lib/python2.7/site-packages.zip/meld/ui/gnomeglade.py:45: Warning: The property GtkAlignment:yscale is deprecated and shouldn't be used anymore. It will be removed in a future version.
/Applications/Meld.app/Contents/Resources/lib/python2.7/site-packages.zip/meld/ui/gnomeglade.py:45: Warning: The property GtkAlignment:left-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.
/Applications/Meld.app/Contents/Resources/lib/python2.7/site-packages.zip/meld/ui/gnomeglade.py:45: Warning: The property GtkImage:stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
/Applications/Meld.app/Contents/Resources/lib/python2.7/site-packages.zip/meld/ui/gnomeglade.py:45: Warning: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
/Applications/Meld.app/Contents/Resources/lib/python2.7/site-packages.zip/meld/ui/gnomeglade.py:45: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.

(meld:93897): Gtk-WARNING **: Could not find the icon 'process-working-symbolic'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases

**Comment by yousseb** [comment]
Please try the latest build osx-7 
The gtk-warnings have been suppressed in this release.

**Comment by aflat** [comment]
That worked great! And thanks for fixing up the Meld script so I can symlink now, much better. I do still get

Couldn't bind the translation domain. Some translations won't work.
'module' object has no attribute 'bind_textdomain_codeset'

Whenever I try to start. Can I install/configure something to get rid of this?

**Comment by yousseb** [comment]
Glad it worked..

As for translation - nope, you can't do anything at the moment to get rid of the message (unless you redirect output to /dev/null). It is on my todo list though. It will be at least a couple of weeks though before I can do anything on this project.

**Comment by aflat** [comment]
k, I'll open another issue on that one.
