### ISSUE TITLE
Info thrown when starting from the command line

### ISSUE THREAD

**Issue by aflat** [yousseb/meld#14]
When starting Meld from the command line, I get

```
Couldn't bind the translation domain. Some translations won't work.
'module' object has no attribute 'bind_textdomain_codeset'
```

**Comment by aflat** [comment]
Looks like upstream knew about this, libintl doesn't seem to come with osx easily. I took the cheap way out for now instead of finding a static linked lib and dropping it in. Instead I edited

/Applications/Meld.app/Contents/Resources/meld

I just commented it out
```
except AttributeError as e:
    # Python builds linked without libintl (i.e., OSX) don't have
    # bindtextdomain(), which causes Gtk.Builder translations to fail.
    #print("Couldn't bind the translation domain. Some translations won't work.")
    #print(e)
```

**Comment by yousseb** [comment]
Eh.. If you want to just silence it. 
I was planning to look into libintl next. If you have any idea where to begin looking, it would be great..

**Comment by yousseb** [comment]
osx-9 fixes this issue. we actually have localization in osx-9 but it's still disabled from the startup script as there are translation files that should be from gnome - not meld - that are not included in our build.
