### ISSUE TITLE
Website .gitconfig info has minor typo

### ISSUE THREAD

**Issue by brian-silverman** [yousseb/meld#17]
On the page:  https://yousseb.github.io/meld/, there are instructions on what to add to .gitconfig to use meld.  There's a minor error.  The line:

`cmd = open -W -a Meld --args --auto-merge \"$PWD/$LOCAL\" \"$PWD/$BASE\" \"$PWD/$REMOTE\" --output \"$PWD/$MERGED\"
`

There should be an equals sign for the `--output` option, that is:

`cmd = open -W -a Meld --args --auto-merge \"$PWD/$LOCAL\" \"$PWD/$BASE\" \"$PWD/$REMOTE\" --output=\"$PWD/$MERGED\"
`

**Comment by yousseb** [comment]
Thanks! Updated.
