### ISSUE TITLE
Meld binary should be signed; is currently not

### ISSUE THREAD

**Issue by sidshetye** [yousseb/meld#19]
The latest binary throws a security warning on OS X 10.11.5 (El Capitan).

> “Meld” can’t be opened because it is from an unidentified developer.

![screen shot 2016-06-20 at 1 37 40 pm](https://cloud.githubusercontent.com/assets/2595088/16209650/da87bf3c-36ec-11e6-81bb-b37e904469ec.png)

It works if you reduce security in Security system preferences to "Allow apps downloaded from" => "Anywhere" but that obviously compromises the rest of the system's signed code security features.

![screen shot 2016-06-20 at 1 41 16 pm](https://cloud.githubusercontent.com/assets/2595088/16209655/e0d90292-36ec-11e6-9868-ba23da9bc72e.png)

**Comment by yousseb** [comment]
Open Anyway does not require Anywhere to be checked. It creates an exception just for Meld. You will have to choose this option for now as I don't have Mac developer account enabled for Mac apps at this point.

**Comment by jjzazuet** [comment]
Hi. I'd add my vote for signing the binaries. I am part of those folks whose work machine is heavily locked down by IT sysadmins, so I can't enter my username/password to override Meld's security level, so I pretty much can't run it :P.

Thanks again for an awesome port!

**Comment by killrazor** [comment]
From macOS User Guide
```
To override your security settings and open the app anyway:

1. In the Finder  on your Mac, locate the app you want to open.

   Don’t use Launchpad to do this. Launchpad doesn’t allow you to access the shortcut menu.

2. Control-click the app icon, then choose Open from the shortcut menu.

3. Click Open.

   The app is saved as an exception to your security settings, and you can open it in the future by double-clicking it just as you can any registered app.```

**Comment by dsbecker** [comment]
That works, but obviously being signed and notarized would be even better.

**Comment by kylelemons** [comment]
Those workarounds (one-time allow and control-clicking the app in Finder) do not work if you are on a Mac that has "Mac app store and identified developers" administratively enforced.
