### ISSUE TITLE
Document command line usage

### ISSUE THREAD

**Issue by mcdemarco** [yousseb/meld#20]
Some indication somewhere that the wrapper script exists and how to use it would be very helpful, since people might not find [the blog comment that mentions it](http://www.alexkras.com/how-to-run-meld-on-mac-os-x-yosemite-without-homebrew-macports-or-think/#comment-55041) and the X11-style file navigation is quite painful on a Mac.

**Comment by NKjoep** [comment]
Yes please document a bit more how to use it from the command line.

With the brew version I am able to do: 

```shell
$ meld index.html otherpage.html
```
check the differences and then continue to work. I'd like to do the same but with this OSX version which looks soooooo much better :)

**Comment by yousseb** [comment]
Try to add this to your .bashrc

```alias meld="/Applications/Meld.app/Contents/MacOS/Meld"```

You should be able to run it from the command line afterwards. Not on my mac right now. If this works, let me know and I'll add it to the docs..

**Comment by yousseb** [comment]
Meld OSX also understands checks for the following environment variables.

```G_ENABLE_DIAGNOSTIC```  ```0``` or ```1```  
```GTK_THEME```  ```Adwaita```  or ```Adwaita:dark```

This can be done by exporting  variable in the wrapper script
```sudo nano /Applications/Meld.app/Contents/MacOS/Meld```

find the part that says
```python
environment = dict(os.environ, **{
    "DYLD_LIBRARY_PATH": ":".join([
        os.path.join(APPPATH, "Resources", "lib"),
        os.path.join(APPPATH, "Frameworks")
    ]),
    "LANG": LANG,
    "LC_ALL": LANG,
    "LC_CTYPE": LANG
})
```

And change it to
```python
environment = dict(os.environ, **{
    "DYLD_LIBRARY_PATH": ":".join([
        os.path.join(APPPATH, "Resources", "lib"),
        os.path.join(APPPATH, "Frameworks")
    ]),
    "LANG": LANG,
    "LC_ALL": LANG,
    "LC_CTYPE": LANG,
    "GTK_THEME":"Adwaita:dark"
})
```

And you'll have a fully dark meld..

**Comment by NKjoep** [comment]
Thank you so much for the hint! :) Meld FTW!

**Comment by NKjoep** [comment]
with this, we can close this issue @yousseb 

` alias meld="/Applications/Meld.app/Contents/MacOS/Meld" `

**Comment by beauraines** [comment]
Could the installer create a symbolic link in `/usr/local/bin` a la
```
 ln -s /Applications/Meld.app/Contents/MacOS/Meld meld
```
