### ISSUE TITLE
macOS X "Meld" wrapper script does not accept "--output <filename>"

### ISSUE THREAD

**Issue by davvid** [yousseb/meld#42]
meld itself uses optparse and accepts both `--output=<filename>` and `--output <filename>`.

The Meld wrapper script only accepts the former.  It should accept the latter form as well.

This issue was originally reported to the Git project[1].

Git may work around the issue in a future version[2], but all Git versions going back to `v1.7.7` use `--output <filename>`, so there's still probably a fair amount of users that would benefit from a fix.

[1] https://public-inbox.org/git/20170619021033.22968-1-davvid@gmail.com/
[2] https://public-inbox.org/git/20170619021033.22968-1-davvid@gmail.com/

**Comment by yousseb** [comment]
https://github.com/yousseb/meld/releases/tag/osx-13 definitely fixes this issue after the removal of the wrapper script.
