### ISSUE TITLE
Continuation of support?

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [yousseb/meld#45]
1st, thanks for the effort in bringing a great linux tool across to the Mac.
OSX has moved on significantly since the last release, and there are various issues that could be resolved.  Is this project still alive?  Last commit is over a year ago.

**Comment by yousseb** [comment]
Not sure how often I can contributed to Meld for OSX. It's mostly a hobby project to me. I pretty much fix it when it breaks though. 
Last release - just now - should fix High Sierra crash (among other things)

**Comment by Napoleon-BlownApart** [comment]
The 3.19.0 (r1) release is working very nicely on High Sierra.  An earlier pointer alignment problem with GTK+ has been fixed.
