### ISSUE TITLE
Step-by-step install instructions for dummies, at UBUNTU 16 LTS

### ISSUE THREAD

**Issue by ppKrauss** [yousseb/meld#47]
Hi, there are some simple and direct instruction like `apt install ./meld.deb` or an step-by-step sequence of **simple and reliable** instructions?

-----

The "for UBUNTU" instructions have no `git clone`  instruction, the README is not complete... And the command not work:

```sh
sudo python3 setup.py install --prefix=/usr
running install
running build
running build_py
copying meld/conf.py-installed -> build/lib/meld/conf.py
running build_scripts
running build_i18n
intltool-update -p -g meld
unable to execute 'intltool-update': No such file or directory
error: command 'intltool-update' failed with exit status 1
```

----

The "apt install" is **ugly** from 2014 when we have 2017's versions!
But, try to install and update, 

1. `sudo apt install meld`  ok, fine and meld is working as 3.14.2.
2. `cd sandbox`  and `git clone git clone https://github.com/GNOME/meld.git`
3. `cd meld` and `sudo python3 setup.py install --prefix=/usr`

The last step produced same expected error,

```
running install
running build
running build_py
copying meld/conf.py-installed -> build/lib/meld/conf.py
running build_scripts
running build_i18n
intltool-update -p -g meld
unable to execute 'intltool-update': No such file or directory
error: command 'intltool-update' failed with exit status 1
```
----

Try also pip `pip install meld --upgrade`, but not detected that have 2017's new version,
"Requirement already up-to-date: meld in /usr/lib/python2.7/dist-packages"

**Comment by yousseb** [comment]
Please post this to the GNOME/master - this fork is for OSX :)

**Comment by ppKrauss** [comment]
Hi @yousseb , thanks the feedback (!)... Hum, there are no meld/issues are, can you help to communicate the problem to GNOME?
