### ISSUE TITLE
Unable to open Meld on macOS High Sierra

### ISSUE THREAD

**Issue by ankit-jha** [yousseb/meld#51]
Unable to open Meld on macOS High Sierra
Tried to open from Terminal
Gives an error

open -a meld
LSOpenURLsWithRole() failed for the application /Applications/Meld.app with error -10810.

**Comment by Doqnach** [comment]
This fixed it also for me:

> I deleted the alias `/Applications/Meld.app/Contents/Frameworks/libz.1.dylib` and now it works.

https://stackoverflow.com/questions/46772116/meld-fails-to-start-after-upgrading-to-10-13-high-sierra

**Comment by henryiii** [comment]
Thanks, deleting that file fixes the issue for me too.

**Comment by 0x-gg** [comment]
Running `unlink /Applications/Meld.app/Contents/Frameworks/libz.1.dylib` fixes it for me too...

via the same SO link posted above

**Comment by itthought** [comment]
You saved my day. Thanks a lot

**Comment by ruslan316** [comment]
thank you!

**Comment by antoniosb** [comment]
awesome!

**Comment by kuldeeptripthee** [comment]
Thanks,Saved my day.

**Comment by yousseb** [comment]
I'm a bit lost, guys.. Are you still getting this with the latest version? I thought I fixed this..

**Comment by yousseb** [comment]
Please try latest..

**Comment by xiaohanhuang** [comment]
Still have similar issue with 3.19:
LSOpenURLsWithRole() failed for the application /Applications/Meld.app with error -600

Remove the file /Applications/Meld.app/Contents/Frameworks/libz.1.dylib didn't help.

**Comment by xiaohanhuang** [comment]
Still have similar issue with 3.19 when using with git:
LSOpenURLsWithRole() failed for the application /Applications/Meld.app with error -600

Remove the file /Applications/Meld.app/Contents/Frameworks/libz.1.dylib didn't help.

**Comment by hautelooknaveen** [comment]
For me, removing /Applications/Meld.app/Contents/Frameworks/libz.1.dylib  did not help... still  unable to open Meld on mac

**Comment by ksa-real** [comment]
3.19 didn't work for me. 3.16 did work after unlinking the `libz.1.dylib`.

**Comment by coelias** [comment]
This doesn't work for me after deleting libz.1.dylib, @yousseb @ankit-jha can you re-open the issue?

**Comment by dansl19** [comment]
this helped me to solve the issue on Majave 

https://gitlab.gnome.org/GNOME/meld/issues/230

**Comment by imransilvake** [comment]
> this helped me to solve the issue on Majave
> 
> https://gitlab.gnome.org/GNOME/meld/issues/230

This worked for me! Thanks

**Comment by thewire247** [comment]
> this helped me to solve the issue on Majave
> 
> https://gitlab.gnome.org/GNOME/meld/issues/230

Uninstalling my old version, then installing the latest version whilst following this post worked for me (OSX Mojave)
