### ISSUE TITLE
Resource File Open

### ISSUE THREAD

**Issue by tiwariPC** [yousseb/meld#56]
Hi, whenever I click Blank file comparison, it opens a resource file on both tabs. I am attaching the screenshot 
![screen shot 2017-12-18 at 15 45 23](https://user-images.githubusercontent.com/25073150/34101103-9d701d98-e40a-11e7-9751-8161b35b40c6.png)

**Comment by yphastos** [comment]
I have the same problem. Pleas fix it.

**Comment by yousseb** [comment]
Fixed in latest release.
