### ISSUE TITLE
Problem with Dock icon integration

### ISSUE THREAD

**Issue by quent** [yousseb/meld#58]
I'm running 3.19.0 on High Sierra.
If I go to the menu Meld > Quit Meld all works perfectly.
However, if I right-click on the Dock icon and then click "Quit" nothing happens.

Maybe somewhat related (or not), I recently had Meld crashing for some obscure reason (after laptop sleep maybe) and then it didn't want to start happily using git difftool.
I managed to kill all the meld-bin that where left around but then again the Meld icon would still show the black dot like it's running. When I tried to reboot later one, it wouldn't let me because it wasn't managing to shut down the Meld application (which wasn't running in any process, like a Zombie app).
It might be worth investigating some aspects of the binary execution <-> Mac Application interface.

**Comment by yousseb** [comment]
Fixed in https://github.com/yousseb/meld/releases/tag/osx-13
