### ISSUE TITLE
Fussy pixel comments

### ISSUE THREAD

**Issue by richb-hanover** [yousseb/meld#6]
I really like Meld - thanks for creating an OSX version. Using Meld 3.15.2 - I have a couple fussy comments about pixels. See the screencast at http://richb-hanover.com/wp-content/uploads/2016/02/MeldScreenSnapz001.ogg for details.

1. The Close button on the About... box appears to be a pixel too low, so that it gets trimmed off.

2. The text at the top and left edge is a tiny bit too close to the window box. It feels cramped. This is especially so when dragging toward the top-left. The grey highlighting that shows you're at top-left touches the text, as shown later in the video.

Proposed solution: move the text in the left-hand pane a couple pixels down/right to give it  a bit more breathing room. Thanks again!

**Comment by yousseb** [comment]
Thanks for the report.

I think this is related to the Mac build missing styles. I'll check it out
over the week-end. I was trying real hard to make the binary build small in
size so I chopped off a bunch of gnome styles and attempted to include only
what is needed. This is probably a missing style.

Thanks again.

**Comment by yousseb** [comment]
Turned out to be GTK+ issue - we're using the version that comes standard with jhbuild..
I upgraded to a newer version and the issues seem to be fixed. I'll ensure that everything works fine then upload a new release.

**Comment by richb-hanover** [comment]
Good Sleuthing! Thanks.
