### ISSUE TITLE
Meld-bin prints application path on every startup

### ISSUE THREAD

**Issue by JMCanning78** [yousseb/meld#67]
First, I should say that I really enjoy having meld on my Mac.  Meld is my favorite difference tool, and it's really helpful to have both the differences between lines and the changes within a line highlighted.

I had some problems using the pre-built OSX binary on one of my Macs, so I switched to using the version installed using `brew cask install meld`.  That got me Meld 3.19.0, and it works from the command line using `meld`.  My issue is that `meld` always prints the path to the application, `/Applications/Meld.app/Contents/MacOS`, at startup.  I think it should only print info like that if some command line option asking for more verbose comments or background information is given.  I would prefer not to see that output line, especially when `meld` is being invoked by `git` for a `difftool` or a `mergetool` operation.  I don't see a similar message when running Meld 3.16.0 on another Mac (where I installed using the pre-build OSX DMG version).

**Comment by yousseb** [comment]
Fixed
