### ISSUE TITLE
Meld doesn't work on Mojave

### ISSUE THREAD

**Issue by SConaway** [yousseb/meld#69]

**Comment by sepehr** [comment]
_"And human kind cried."_

**Comment by SConaway** [comment]
NVM that. Works on the GM now.

**Comment by fragno** [comment]
seems not work again in the final release mojova?

**Comment by SConaway** [comment]
Seems to work to me on `18B73a`.On Oct 30, 2018, at 2:13 AM, fragno <notifications@github.com> wrote:seems not work again in the final release mojova?—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by SConaway** [comment]
Seems to work to me on `18B73a`.

**Comment by dansl19** [comment]
Fixed the issue : https://gitlab.gnome.org/GNOME/meld/issues/230

**Comment by cscetbon** [comment]
It doesn't work for me on sha256 81f79
