### ISSUE TITLE
Would love a dark theme on MacOS version.

### ISSUE THREAD

**Issue by decentralizeduser** [yousseb/meld#71]
Hi, not an issue, but would love to see a dark theme for MacOS :-)

**Comment by yousseb** [comment]
Check the website: https://yousseb.github.io/meld/ for instructions. :)

**Comment by decentralizeduser** [comment]
Hey thanks for pointing that out .. fantastic  :-)

**Comment by KaKi87** [comment]
Hi,
It would be nice to be able to set theme using GUI settings, and for the app to use the system setting by default.
Thanks
