### ISSUE TITLE
Fonts for file comparison on MAC

### ISSUE THREAD

**Issue by pablorocamartin** [yousseb/meld#72]
Hi there, I'm having a lot of font issues with meld on MAC OSX High Sierra. I'm not being able to to make meld to looks nice when comparing files. I have a question about the screenshot attached in 
https://yousseb.github.io/meld/ . That Screenshot is for a Mac OS , can I know which font is used in the screenshot attached ? . The attachment looks fine on the page and is the setup that I would like to use but I'm not finding a font that looks like the one used in the screenshot. I'm using 3.19.2. Thanks

**Comment by yousseb** [comment]
I don't really remember what that font was. For now, I'm using:

`brew tap caskroom/fonts && brew cask install font-source-code-pro`

Then using the `Source Code Pro Regular` font @10
