### ISSUE TITLE
3.19.2-r6,osx-15 break the meld command line 

### ISSUE THREAD

**Issue by number5** [yousseb/meld#76]
On High Sierra 10.13.6, running 
`meld` from command line ends with following error
```
2018-12-31 14:26:41.468 meld[31294:5556591] The Info.plist file must have a PyRuntimeLocations array containing string values for preferred Python runtime locations.  These strings should be "otool -L" style mach ids; "@executable_stub" and "~" prefixes will be translated accordingly.
```
`meld` is a symbolic link to Meld binary
```
lrwxr-xr-x 42 bruce 31 Dec 10:40 /usr/local/bin/meld -> /Applications/Meld.app/Contents/MacOS/Meld
```

I can launch the GUI with `open -a Meld` and reverted back to 3.19.0 works

**Comment by yousseb** [comment]
Try adding the following to your `~/.bashrc`
```
alias meld="/Applications/Meld.app/Contents/MacOS/Meld"
```
and delete the symlink. Once added to you `~/.bashrc`, issue the command `source ~/.bashrc` to activate it in the current Terminal.

**Comment by number5** [comment]
@yousseb thanks, `alias` solved the issue.

**Comment by Stargator** [comment]
Worked for me too! I had recently upgraded meld too.

Just FYI @yousseb this is the version I had and what it was upgraded to: `meld 3.19.2-r3,osx-12 -> 3.19.2-r6,osx-15`
