### ISSUE TITLE
Are OSX build instructions out of date?

### ISSUE THREAD

**Issue by alpiepho** [yousseb/meld#88]
It looks like the gtk-osx project was moved from Github to Gitlab, so the paths are different.  It also looks like the  gtk-osx-build-setup.sh file is missing in master at https://gitlab.gnome.org/GNOME/gtk-osx/.  There is a branch 'Last-Lion' that has the script, but I have not had much success running it.

Can you offer any insight or advice on how to build meld for mac?  I was hoping to look at some the strange behavior with Mojave.

**Comment by yousseb** [comment]
They are now.
