### ISSUE TITLE
meld for merging too

### ISSUE THREAD

**Issue by Gruntfuggly** [yousseb/meld#9]
Hi there

First - thanks for providing this package of meld for OSX - I use it all the time.

On the new website (https://yousseb.github.io/meld/) you've given details of how to set up meld as a git difftool. Just thought you might want to add details for using it as a merge tool aswell - seeing as it's really good at it!

```
[mergetool “meld”]
    cmd = open -W -a Meld –args –auto-merge $PWD/$LOCAL $PWD/$BASE $PWD/$REMOTE –output $PWD/$MERGED
```

**Comment by yousseb** [comment]
Can you try the following setup please and let me know if it works?

```
[diff]
        tool = meld
				
[difftool]
        prompt = false
				
[difftool "meld"]
        trustExitCode = true
        cmd = open -W -a Meld --args \"$LOCAL\" \"$PWD/$REMOTE\"
[merge]
        tool = meld
				
[mergetool]
        prompt = false

[mergetool "meld"]
        trustExitCode = true
        cmd = open -W -a Meld --args --auto-merge \"$PWD/$LOCAL\" \"$PWD/$BASE\" \"$PWD/$REMOTE\" –output \"$PWD/$MERGED\"
```

I tried the diff part pretty quickly and it seems fine. I just don't have the time to try the merge part.

**Comment by Gruntfuggly** [comment]
> On 25 Feb 2016, at 11:27, Youssef A. Abou-Kewik <notifications@github.com> wrote:
> 
> Can you try the following setup please and let me know if it works?
> 
> [diff]
>         tool = meld
> 
> [difftool]
>         prompt = false
> 
> [difftool "meld"]
>         trustExitCode = true
>         cmd = open -W -a Meld --args \"$LOCAL\" \"$PWD/$REMOTE\"
> [merge]
>         tool = meld
> 
> [mergetool]
>         prompt = false
> 
> [mergetool "meld"]
>         trustExitCode = true
>         cmd = open -W -a Meld --args --auto-merge \"$PWD/$LOCAL\" \"$PWD/$BASE\" \"$PWD/$REMOTE\" –output \"$PWD/$MERGED\"
> 
> I tried the diff part pretty quickly and it seems fine. I just don't have the time to try the merge part.
> 

Hi Youssef

The ‘–‘ in front of output is wrong (is it a hyphen?). It needs two dashes. If I replace it with two dashes, it works correctly:

> [mergetool "meld"]
>         trustExitCode = true
>         cmd = open -W -a Meld --args --auto-merge \"$PWD/$LOCAL\" \"$PWD/$BASE\" \"$PWD/$REMOTE\” --output \"$PWD/$MERGED\"


Cheers,
Nigel

**Comment by yousseb** [comment]
Done. Thanks, Nigel.
