### ISSUE TITLE
Latest OSX patch breaks meld

### ISSUE THREAD

**Issue by DouglasPearless** [yousseb/meld#91]
Just updated to Mojave 10.14.6 cause Meld to not display the first screen, and directory comparisons can no longer select directories.

Console log follows:

default	22:43:03.024060 +1200	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : Meld
error	22:43:03.122669 +1200	tccd	Failed to copy signing info for 697, responsible for file:///Applications/Meld.app/Contents/MacOS/Meld: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"
default	22:43:03.124972 +1200	launchservicesd	CHECKIN:0x0-0x55055 697 org.gnome.meld
default	22:43:03.126658 +1200	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier org.gnome.meld, type: 0: 0x7f9ca5003430 at /Applications/Meld.app
default	22:43:03.127282 +1200	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : Meld
default	22:43:05.248815 +1200	Meld	OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(aevt,oapp handler=0x1000fefc0 isSys=NO) err=0/noErr
default	22:43:05.248839 +1200	Meld	OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(aevt,odoc handler=0x1000fef90 isSys=NO) err=0/noErr
default	22:43:05.248876 +1200	Meld	OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(GURL,GURL handler=0x1000fef60 isSys=NO) err=0/noErr
default	22:43:05.470659 +1200	Meld	Current system appearance, (HLTB: 1), (SLS: 0)
default	22:43:05.472887 +1200	Meld	Post-registration system appearance: (HLTB: 1)
default	22:43:05.475477 +1200	distnoted	register name: com.apple.xctest.FakeForceTouchDevice object: org.gnome.meld token: f4279 pid: 697
default	22:43:05.479700 +1200	loginwindow	-[PersistentAppsSupport applicationReady:] | App: Meld, ready, updating active tracking timer
default	22:43:06.439019 +1200	Meld	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x60000211d4f0
 (
    "<NSAquaAppearance: 0x6000017316c0>",
    "<NSSystemAppearance: 0x600001731a80>"
)>
default	22:43:06.452240 +1200	distnoted	register name: com.apple.nsquiet_safe_quit_give_reason object: org.gnome.meld token: f4298 pid: 697
error	22:43:06.524150 +1200	Meld	flock failed to lock maps file: errno = 35
error	22:43:06.524192 +1200	Meld	flock failed to lock maps file: errno = 35
error	22:43:06.559117 +1200	Meld	flock failed to lock maps file: errno = 35
error	22:43:06.559161 +1200	Meld	flock failed to lock maps file: errno = 35
error	22:43:06.634311 +1200	Meld	<private>
error	22:43:06.634341 +1200	Meld	<private>
default	22:43:06.637237 +1200	Meld	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 161 vs 261, 512, <private>
default	22:43:06.699747 +1200	hidd	Connection added: IOHIDEventSystemConnection uuid:9072179D-F675-4B46-9DAC-CF135E640381 pid:697 process:Meld type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) inactive:1
default	22:43:10.483671 +1200	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : Meld
default	22:43:10.483695 +1200	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: Meld
default	22:43:10.483736 +1200	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: Meld
default	22:43:10.489795 +1200	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Contents:(
        {
        BackgroundState = 0;
        BundleID = "org.gnome.meld";
        Hide = 0;
        Path = "/Applications/Meld.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.console";
        Hide = 0;
        Path = "/Applications/Utilities/Console.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.systempreferences";
        Hide = 0;
        Path = "/Applications/System Preferences.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.safari";
        Hide = 0;
        Path = "/Applications/Safari.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    }
)
default	22:43:16.511708 +1200	Meld	LSExceptions shared instance invalidated for timeout.
default	22:43:29.346447 +1200	Meld	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 130 vs 161, 513, <private>

**Comment by fiendish** [comment]
> Meld to not display the first screen

Do you mean a splash screen or the new comparison screen? 

> and directory comparisons can no longer select directories.

This works for me.

**Comment by DouglasPearless** [comment]
interestingly, it was the first screen, now after another update t simply takes about 30 seconds for the first screen to appear; weird!

**Comment by yousseb** [comment]
Latest 21.osxr3 should be working on Mojave and Catalina. Closing this issue.
