### ISSUE TITLE
doesn't run on OSX

### ISSUE THREAD

**Issue by pwvirgo** [yousseb/meld#92]
fyi - i don't know python so I don't have any insights into this error.  Tried running by downloading zip file and following instructions in README.MD
  
pwv ~ $ python3 a/mac-ots/meld-master/bin/meld 
Traceback (most recent call last):
  File "a/mac-ots/meld-master/bin/meld", line 93, in <module>
    import meld.conf  # noqa: E402
  File "/Users/pwv/a/mac-ots/meld-master/meld/conf.py", line 51
    os.environ['G_RESOURCE_OVERLAYS'] = f'{RESOURCE_BASE}={resource_path}'
                                                                         ^
SyntaxError: invalid syntax
pwv ~ $

System Software Overview:
  System Version:	macOS 10.14.6 (18G87)
  Kernel Version:	Darwin 18.7.0

pwv ~ $ python3
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by yousseb** [comment]
I updated the build instructions..

In order to run from source, you will need to follow the build instructions and then:

```
~/.new_local/bin/jhbuild run bin/meld
```
